<?php namespace Mohsen\IPay;

class IPayMellatException extends \Exception
{
    protected $errors = array(
        'en' => array(
            11 => 'Invalid Card Number',
            12 => 'No Sufficient Funds',
            13 => 'Incorrect Pin',
            14 => 'Allowable Number Of Pin Tries Exceeded',
            15 => 'Card Not Effective',
            16 => 'Exceeds Withdrawal Frequency Limit',
            17 => 'Customer Cancellation',
            18 => 'Expired Card',
            19 => 'Exceeds Withdrawal Amount Limit',
            111 => 'No Such Issuer',
            112 => 'Card Switch Internal Error',
            113 => 'Issuer Or Switch Is Inoperative',
            114 => 'Transaction Not Permitted To Card Holder',
            21 => 'Invalid Merchant',
            23 => 'Security Violation',
            24 => 'Invalid User Or Password',
            25 => 'Invalid Amount',
            31 => 'Invalid Response',
            32 => 'Format Error',
            33 => 'No Investment Account',
            34 => 'System Internal Error',
            35 => 'Invalid Business Date',
            41 => 'Duplicate Order Id',
            42 => 'Sale Transaction Not Found',
            43 => 'Duplicate Verify',
            44 => 'Verify Transaction Not Found',
            45 => 'Transaction Has Been Settled',
            46 => 'Transaction Has Not Been Settled',
            47 => 'Settle Transaction Not Found',
            48 => 'Transaction Has Been Reversed',
            49 => 'Refund Transaction Not Found',
            412 => 'Bill Digit Incorrect',
            413 => 'Payment Digit Incorrect',
            414=> 'Bill Organization Not Valid',
            415 => 'Session Timeout',
            416 => 'Data Access Exception',
            417 => 'Payer Id Is Invalid',
            418 => 'Customer Not Found',
            419 => 'Try Count Exceeded',
            421 => 'Invalid IP',
            51 => 'Duplicate Transmission',
            54 => 'Original Transaction Not Found',
            55 => 'Invalid Transaction',
            61 => 'Error In Settle'
        ),

        'fa' => array(
            11 => 'شماره کارت نامعتبر است',
            12 => 'موجودی کافی نیست',
            13 => 'رمز نادرست است',
            14 => 'تعداد دفعات وارد کردن رمز بیش از حد مجاز است',
            15 => 'کارت نامعتبر است',
            16 => 'دفعات برداشت وجه بیش از حد مجاز است',
            17 => 'کاربر از انجام تراکنش منصرف شده است',
            18 => 'تاریخ انقضای کارت گذشته است',
            19 => 'مبلغ برداشت وجه بیش از حد مجاز است',
            111 => 'صادر کننده کارت نامعتبر است',
            112 => 'خطای سوییچ صادر کننده کارت',
            113 => 'پاسخی از صادر کننده کارت دریافت نشد',
            114 => 'دارنده این کارت مجاز به انجام این تراکنش نیست',
            21 => 'پذیرنده نامعتبر است',
            23 => 'خطای امنیتی رخ داده است',
            24 => 'اطلاعات کاربری پذیرنده نامعتبر است',
            25 => 'مبلغ نامعتبر است',
            31 => 'پاسخ نامعتبر است',
            32 => 'فرمت اطلاعات وارد شده صحیح نمی‌باشد',
            33 => 'حساب نامعتبر است',
            34 => 'خطای سیستمی',
            35 => 'تاریخ نامعتبر است',
            41 => 'شماره درخواست تکراری است',
            42 => 'تراکنش Sale یافت نشد',
            43 => 'قبلا درخواست Verfiy داده شده است',
            44 => 'درخواست Verfiy یافت نشد',
            45 => 'تراکنش Settle شده است',
            46 => 'تراکنش Settle نشده است',
            47 => 'تراکنش Settle یافت نشد',
            48 => 'تراکنش Reverse شده است',
            49 => 'تراکنش Refund یافت نشد.',
            412 => 'شناسه قبض نادرست است',
            413 => 'شناسه پرداخت نادرست است',
            414=> 'سازمان صادر کننده قبض نامعتبر است',
            415 => 'زمان جلسه کاری به پایان رسیده است',
            416 => 'خطا در ثبت اطلاعات',
            417 => 'شناسه پرداخت کننده نامعتبر است',
            418 => 'اشکال در تعریف اطلاعات مشتری',
            419 => 'تعداد دفعات ورود اطلاعات از حد مجاز گذشته است',
            421 => 'IP نامعتبر است',
            51 => 'تراکنش تکراری است',
            54 => 'تراکنش مرجع موجود نیست',
            55 => 'تراکنش نامعتبر است',
            61 => 'خطا در واریز'
        )
    );

    public function __construct($errorId, $language = 'en')
    {
        $this->errorId = $errorId;

        parent::__construct($this->errors[$language][$errorId].' #'.$errorId, $errorId);
    }
}
